---
deployment:
  tasks:
    - export DEPLOYPATH=/mnt/volume_fra1_01/fagnooneg/public_html/trips/fagnoon-trips/
    - echo "Minimal .cpanel.yml executed at $(date)" > $DEPLOYPATH/deployment_debug.txt

