name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: laravel_test
        ports:
          - 3306:3306
        options: >- # Ensure this is indented correctly
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    strategy:
      matrix:
        php-version: [8.2]

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, bcmath, pdo_mysql

    - name: Copy .env and configure DB creds
      run: |
        cp .env.example .env
        sed -i "s/DB_DATABASE=laravel/DB_DATABASE=laravel_test/g" .env
        sed -i "s/DB_USERNAME=forge/DB_USERNAME=root/g" .env
        sed -i "s/DB_PASSWORD=/DB_PASSWORD=/g" .env

    - name: Install Dependencies
      run: composer install --no-progress --no-suggest

    - name: Generate App Key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run Migrations
      run: php artisan migrate --force

    - name: Run Tests
      run: php artisan test --verbose

